### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by bastelfreak**
this will be a collection of smaller changes, cleanups, fixes (you may call it: dev branch)

### CODE REVIEW

**Comment by bastelfreak** [comment]
here we can also validate everything against shellcheck https://github.com/virtapi/LARS/issues/10

**Comment by Bluewind** [comment]
Please merge combine 1c31db5 and 3d44551 (the extract_archiso.sh ones) before you merge this. Also you should really update the readme at the same time as you move/add files.

**Comment by Bluewind** [comment]
looks good

**Comment by bastelfreak** [comment]
\o/

**Pull request merged**
